// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Request data for generating a notification.
/// Maps to the Kotlin SDK's NotificationRequest model.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotificationRequest {
  /// The fallback message if AI fails
  var baseMessage: String
  /// Additional context data about the base_message (e.g., "delivery", "messaging")
  var context: String
  /// The API key for authentication
  var apiKey: String
  /// Intent identifier from SDK (optional, will be generated if not provided)
  var intentId: String? = nil
  /// User locale (defaults to "en-US")
  var locale: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationRequest? {
    let baseMessage = pigeonVar_list[0] as! String
    let context = pigeonVar_list[1] as! String
    let apiKey = pigeonVar_list[2] as! String
    let intentId: String? = nilOrValue(pigeonVar_list[3])
    let locale = pigeonVar_list[4] as! String

    return NotificationRequest(
      baseMessage: baseMessage,
      context: context,
      apiKey: apiKey,
      intentId: intentId,
      locale: locale
    )
  }
  func toList() -> [Any?] {
    return [
      baseMessage,
      context,
      apiKey,
      intentId,
      locale,
    ]
  }
}

/// Response data from notification generation.
/// Maps to the Kotlin SDK's NotificationResponse model.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotificationResponse {
  /// The variant ID used for A/B testing
  var variantId: String
  /// The optimized notification message
  var resolvedMessage: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationResponse? {
    let variantId = pigeonVar_list[0] as! String
    let resolvedMessage = pigeonVar_list[1] as! String

    return NotificationResponse(
      variantId: variantId,
      resolvedMessage: resolvedMessage
    )
  }
  func toList() -> [Any?] {
    return [
      variantId,
      resolvedMessage,
    ]
  }
}

/// Request data for recording a metric event.
/// Maps to the Kotlin SDK's MetricRequest model.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MetricRequest {
  /// The variant ID returned from generateNotificationBody
  var variantId: String
  /// The type of event: "sent" or "clicked"
  var eventType: String
  /// Optional ISO 8601 timestamp (defaults to current time if not provided)
  var timestamp: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MetricRequest? {
    let variantId = pigeonVar_list[0] as! String
    let eventType = pigeonVar_list[1] as! String
    let timestamp: String? = nilOrValue(pigeonVar_list[2])

    return MetricRequest(
      variantId: variantId,
      eventType: eventType,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      variantId,
      eventType,
      timestamp,
    ]
  }
}

/// Response data from metric recording.
/// Maps to the Kotlin SDK's MetricResponse model.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MetricResponse {
  /// Status of the metric recording (typically "ok")
  var status: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MetricResponse? {
    let status = pigeonVar_list[0] as! String

    return MetricResponse(
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      status
    ]
  }
}

/// Error information for PushBunny operations.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PushBunnyError {
  /// Error code (e.g., "NETWORK_ERROR", "API_ERROR", "INVALID_REQUEST")
  var code: String
  /// Human-readable error message
  var message: String
  /// Additional error details (optional)
  var details: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PushBunnyError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let details: String? = nilOrValue(pigeonVar_list[2])

    return PushBunnyError(
      code: code,
      message: message,
      details: details
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      details,
    ]
  }
}

private class PushBunnyPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NotificationRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return NotificationResponse.fromList(self.readValue() as! [Any?])
    case 131:
      return MetricRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return MetricResponse.fromList(self.readValue() as! [Any?])
    case 133:
      return PushBunnyError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PushBunnyPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NotificationRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NotificationResponse {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? MetricRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MetricResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PushBunnyError {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PushBunnyPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PushBunnyPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PushBunnyPigeonPigeonCodecWriter(data: data)
  }
}

class PushBunnyPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PushBunnyPigeonPigeonCodec(readerWriter: PushBunnyPigeonPigeonCodecReaderWriter())
}


/// Host API for PushBunny operations.
/// This interface is implemented on the native platform (Android/iOS)
/// and called from Dart.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PushBunnyApi {
  /// Generates an optimized notification message using the PushBunny backend.
  ///
  /// This method calls the Kotlin SDK's generateNotificationBody function.
  ///
  /// Throws a PlatformException on error with details from PushBunnyError.
  func generateNotification(request: NotificationRequest, completion: @escaping (Result<NotificationResponse, Error>) -> Void)
  /// Records a notification metric event to the PushBunny backend.
  ///
  /// This method tracks notification lifecycle events (sent, clicked) for A/B testing
  /// and analytics purposes. The backend uses these metrics to determine which notification
  /// variants perform best.
  ///
  /// This method calls the Kotlin SDK's recordMetric function.
  ///
  /// Throws a PlatformException on error with details from PushBunnyError.
  func recordMetric(request: MetricRequest, completion: @escaping (Result<MetricResponse, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PushBunnyApiSetup {
  static var codec: FlutterStandardMessageCodec { PushBunnyPigeonPigeonCodec.shared }
  /// Sets up an instance of `PushBunnyApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PushBunnyApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Generates an optimized notification message using the PushBunny backend.
    ///
    /// This method calls the Kotlin SDK's generateNotificationBody function.
    ///
    /// Throws a PlatformException on error with details from PushBunnyError.
    let generateNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fluttersdk.PushBunnyApi.generateNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NotificationRequest
        api.generateNotification(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateNotificationChannel.setMessageHandler(nil)
    }
    /// Records a notification metric event to the PushBunny backend.
    ///
    /// This method tracks notification lifecycle events (sent, clicked) for A/B testing
    /// and analytics purposes. The backend uses these metrics to determine which notification
    /// variants perform best.
    ///
    /// This method calls the Kotlin SDK's recordMetric function.
    ///
    /// Throws a PlatformException on error with details from PushBunnyError.
    let recordMetricChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fluttersdk.PushBunnyApi.recordMetric\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recordMetricChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! MetricRequest
        api.recordMetric(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recordMetricChannel.setMessageHandler(nil)
    }
  }
}
