// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Request data for generating a notification.
/// Maps to the Kotlin SDK's NotificationRequest model.
class NotificationRequest {
  NotificationRequest({
    required this.baseMessage,
    required this.context,
    required this.apiKey,
    this.intentId,
    this.locale = 'en-US',
  });

  /// The fallback message if AI fails
  String baseMessage;

  /// Additional context data about the base_message (e.g., "delivery", "messaging")
  String context;

  /// The API key for authentication
  String apiKey;

  /// Intent identifier from SDK (optional, will be generated if not provided)
  String? intentId;

  /// User locale (defaults to "en-US")
  String locale;

  Object encode() {
    return <Object?>[
      baseMessage,
      context,
      apiKey,
      intentId,
      locale,
    ];
  }

  static NotificationRequest decode(Object result) {
    result as List<Object?>;
    return NotificationRequest(
      baseMessage: result[0]! as String,
      context: result[1]! as String,
      apiKey: result[2]! as String,
      intentId: result[3] as String?,
      locale: result[4]! as String,
    );
  }
}

/// Response data from notification generation.
/// Maps to the Kotlin SDK's NotificationResponse model.
class NotificationResponse {
  NotificationResponse({
    required this.variantId,
    required this.resolvedMessage,
  });

  /// The variant ID used for A/B testing
  String variantId;

  /// The optimized notification message
  String resolvedMessage;

  Object encode() {
    return <Object?>[
      variantId,
      resolvedMessage,
    ];
  }

  static NotificationResponse decode(Object result) {
    result as List<Object?>;
    return NotificationResponse(
      variantId: result[0]! as String,
      resolvedMessage: result[1]! as String,
    );
  }
}

/// Error information for PushBunny operations.
class PushBunnyError {
  PushBunnyError({
    required this.code,
    required this.message,
    this.details,
  });

  /// Error code (e.g., "NETWORK_ERROR", "API_ERROR", "INVALID_REQUEST")
  String code;

  /// Human-readable error message
  String message;

  /// Additional error details (optional)
  String? details;

  Object encode() {
    return <Object?>[
      code,
      message,
      details,
    ];
  }

  static PushBunnyError decode(Object result) {
    result as List<Object?>;
    return PushBunnyError(
      code: result[0]! as String,
      message: result[1]! as String,
      details: result[2] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NotificationRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NotificationResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PushBunnyError) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NotificationRequest.decode(readValue(buffer)!);
      case 130: 
        return NotificationResponse.decode(readValue(buffer)!);
      case 131: 
        return PushBunnyError.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for PushBunny operations.
/// This interface is implemented on the native platform (Android/iOS)
/// and called from Dart.
class PushBunnyApi {
  /// Constructor for [PushBunnyApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PushBunnyApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generates an optimized notification message using the PushBunny backend.
  ///
  /// This method calls the Kotlin SDK's generateNotificationBody function.
  ///
  /// Throws a PlatformException on error with details from PushBunnyError.
  Future<NotificationResponse> generateNotification(NotificationRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluttersdk.PushBunnyApi.generateNotification$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NotificationResponse?)!;
    }
  }
}
