// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.inotter.pushbunnyflutter.fluttersdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Request data for generating a notification.
 * Maps to the Kotlin SDK's NotificationRequest model.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NotificationRequest (
  /** The fallback message if AI fails */
  val baseMessage: String,
  /** Additional context data about the base_message (e.g., "delivery", "messaging") */
  val context: String,
  /** The API key for authentication */
  val apiKey: String,
  /** Intent identifier from SDK (optional, will be generated if not provided) */
  val intentId: String? = null,
  /** User locale (defaults to "en-US") */
  val locale: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationRequest {
      val baseMessage = pigeonVar_list[0] as String
      val context = pigeonVar_list[1] as String
      val apiKey = pigeonVar_list[2] as String
      val intentId = pigeonVar_list[3] as String?
      val locale = pigeonVar_list[4] as String
      return NotificationRequest(baseMessage, context, apiKey, intentId, locale)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      baseMessage,
      context,
      apiKey,
      intentId,
      locale,
    )
  }
}

/**
 * Response data from notification generation.
 * Maps to the Kotlin SDK's NotificationResponse model.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NotificationResponse (
  /** The variant ID used for A/B testing */
  val variantId: String,
  /** The optimized notification message */
  val resolvedMessage: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationResponse {
      val variantId = pigeonVar_list[0] as String
      val resolvedMessage = pigeonVar_list[1] as String
      return NotificationResponse(variantId, resolvedMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      variantId,
      resolvedMessage,
    )
  }
}

/**
 * Request data for recording a metric event.
 * Maps to the Kotlin SDK's MetricRequest model.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MetricRequest (
  /** The variant ID returned from generateNotificationBody */
  val variantId: String,
  /** The type of event: "sent" or "clicked" */
  val eventType: String,
  /** Optional ISO 8601 timestamp (defaults to current time if not provided) */
  val timestamp: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MetricRequest {
      val variantId = pigeonVar_list[0] as String
      val eventType = pigeonVar_list[1] as String
      val timestamp = pigeonVar_list[2] as String?
      return MetricRequest(variantId, eventType, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      variantId,
      eventType,
      timestamp,
    )
  }
}

/**
 * Response data from metric recording.
 * Maps to the Kotlin SDK's MetricResponse model.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MetricResponse (
  /** Status of the metric recording (typically "ok") */
  val status: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MetricResponse {
      val status = pigeonVar_list[0] as String
      return MetricResponse(status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
    )
  }
}

/**
 * Error information for PushBunny operations.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PushBunnyError (
  /** Error code (e.g., "NETWORK_ERROR", "API_ERROR", "INVALID_REQUEST") */
  val code: String,
  /** Human-readable error message */
  val message: String,
  /** Additional error details (optional) */
  val details: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushBunnyError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val details = pigeonVar_list[2] as String?
      return PushBunnyError(code, message, details)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      details,
    )
  }
}
private open class PushBunnyPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationResponse.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MetricRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MetricResponse.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushBunnyError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NotificationRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NotificationResponse -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is MetricRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MetricResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PushBunnyError -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for PushBunny operations.
 * This interface is implemented on the native platform (Android/iOS)
 * and called from Dart.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PushBunnyApi {
  /**
   * Generates an optimized notification message using the PushBunny backend.
   *
   * This method calls the Kotlin SDK's generateNotificationBody function.
   *
   * Throws a PlatformException on error with details from PushBunnyError.
   */
  fun generateNotification(request: NotificationRequest, callback: (Result<NotificationResponse>) -> Unit)
  /**
   * Records a notification metric event to the PushBunny backend.
   *
   * This method tracks notification lifecycle events (sent, clicked) for A/B testing
   * and analytics purposes. The backend uses these metrics to determine which notification
   * variants perform best.
   *
   * This method calls the Kotlin SDK's recordMetric function.
   *
   * Throws a PlatformException on error with details from PushBunnyError.
   */
  fun recordMetric(request: MetricRequest, callback: (Result<MetricResponse>) -> Unit)

  companion object {
    /** The codec used by PushBunnyApi. */
    val codec: MessageCodec<Any?> by lazy {
      PushBunnyPigeonPigeonCodec()
    }
    /** Sets up an instance of `PushBunnyApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PushBunnyApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluttersdk.PushBunnyApi.generateNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NotificationRequest
            api.generateNotification(requestArg) { result: Result<NotificationResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluttersdk.PushBunnyApi.recordMetric$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as MetricRequest
            api.recordMetric(requestArg) { result: Result<MetricResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
